version: 2
jobs:
  test_hello:
      working_directory: ~/hello
      docker:
        - image: circleci/node:12.13.1
      steps:
        - checkout
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              cd util
              chmod +x common.sh
              chmod +x run_tests.sh
              ./run_tests.sh

  build_hello:
      working_directory: ~/hello
      docker:
        - image: circleci/node:12.13.1
      steps:
        - checkout
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              sudo apt-get install ruby-full jq
              cd util
              chmod +x build_push_docker.sh
              ./build_push_docker.sh
workflows:
  version: 2
  build:
    jobs:
        - test_hello
        - build_hello:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - test

