version: 2
jobs:
  build_hello:
      working_directory: ~/hello
      docker:
        - image: circleci/node:12.13.1
      steps:
        - checkout
        - run:
          name: "hello build"
          command: |
            cd docker
            chmod +x build_push_docker.sh
            ./build_push_docker.sh
