version: 2
jobs:
  build_hello:
      working_directory: ~/hello
      docker:
        - image: circleci/node:12.13.1
      steps:
        - checkout
        - run:
          name: Move to docker folder
          command: cd docker
        - run:
          name: Make script executable
          command: chmod +x build_push_docker.sh
        - run:
          name: Build packages with docker-compose and push to registry
          command: ./build_push_docker.sh
            
workflows:
  version: 2
  build:
    jobs:
      - build_hello
