version: 2.1

executors:
  hello-executor:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/hello

jobs:
  test_hello:
      executor: hello-executor
      steps:
        - checkout
        - run:
            name: Run tests
            command: |
              sudo apt-get install jq
              cd util
              chmod +x common.sh
              chmod +x run_tests.sh
              ./run_tests.sh

  build_hello:
      executor: hello-executor
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              sudo apt-get install ruby-full jq
              cd util
              chmod +x build_push_docker.sh
              ./build_push_docker.sh
        - persist_to_workspace:
              root: ./util
              paths:
                - .env

  deploy_hello:
      executor: hello-executor
      steps:
        - checkout
        - attach_workspace:
            at: ./util
        - run:
            name: Fake deploy
            command: |
              ls -lah ./util/
              cat ./util/docker-compose.yaml

workflows:
  version: 2
  build:
    jobs:
        - test_hello
        - build_hello:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - test_hello
        - deploy_hello:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - build_hello
